spring.datasource.url=jdbc:postgresql://localhost:5432/Pos_system
spring.datasource.username=postgres
spring.datasource.password=@Einsteinzac09
spring.datasource.driver-class-name=org.postgresql.Driver

# Automatically updates the database schema based on your @Entity classes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true